### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by avukalov** [priyanshu-panwar/fastapi-utilities#18]
Trying to run example with _async_  `repeat_at` function. 

```
from fastapi import FastAPI
from contextlib import asynccontextmanager
from fastapi_utilities import repeat_every, repeat_at


@asynccontextmanager
async def lifespan(app: FastAPI):
    # --- startup ---
    await test()
    await test2()  # ------------- await added here
    yield
    # --- shutdown ---


app = FastAPI(lifespan=lifespan)


# Repeat Every Example
@repeat_every(seconds=2)
async def test():
    print("test")


# Repeat At Example
@repeat_at(cron="* * * * *")
async def test2():  # ------------- async added here
    print("test2")
```

After executing command `fastapi dev main.py` I got this error: 

```
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "C:\workspace\Learning\FastAPI\.venv\Lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\Learning\FastAPI\main.py", line 11, in lifespan
    await test2()  # ------------- await added here
    ^^^^^^^^^^^^^
TypeError: object NoneType can't be used in 'await' expression

test
ERROR:    Application startup failed. Exiting.
```

versions: 
fastapi           0.111.0
fastapi-utilities 0.2.0

**Comment by Scoowy** [comment]
Same problem.

**Comment by priyanshu-panwar** [comment]
Hi @Scoowy 
I am looking into the issue.
Can you please `repeat_every` till then.

**Comment by apoplexi24** [comment]
Pull Request for Issue #18 -
https://github.com/priyanshu-panwar/fastapi-utilities/pull/27


Description -

I've refactored the repeat_at decorator to better handle both async and sync functions. Instead of having a single wrapper, I now use async_wrapper for coroutines and sync_wrapper for regular functions, which ensures proper execution. The old approach of checking if the function was a coroutine inside the loop was unnecessary, so I cleaned that up.

I also fixed some naming inconsistencies (repititions → repetitions, sleepTime → sleep_time) and improved error handling. Now, invalid cron expressions raise an error immediately instead of failing silently. Logging is also more reliable, making sure exceptions are either logged or raised based on the raise_exceptions flag.

The error you're encountering, TypeError: object NoneType can't be used in 'await' expression, typically arises when attempting to await a function that returns None instead of a coroutine. This situation often occurs when using decorators that modify the behavior of asynchronous functions.


**Understanding the Issue**

In your code, the @repeat_at decorator is designed to schedule functions to run at specific intervals based on a cron expression. However, when this decorator is applied to an asynchronous function, it wraps the function in such a way that the original function is scheduled to run periodically, but the wrapper itself does not return a coroutine. Consequently, if you try to await the decorated function, you'll encounter a NoneType error because the wrapper returns None.


**Solution**

To resolve this issue, you can separate the scheduling of the repeated task from the definition of the asynchronous function. This approach allows you to maintain the original asynchronous function for direct invocation while using a separate function to handle the scheduling.

Test cases were updated to match these changes, ensuring both async and sync versions are properly tested.
